### ISSUE TITLE
Is dependence condition missing in compose.folders.yml for pulp_web service

### ISSUE THREAD

**Issue by xm1234567** [pulp/pulp-oci-images#574]
**Version**
pulp/pulp-minimal   latest    f89cae78c76a  
pulp/pulp-web       latest    69a0e8f150cc  

**Describe the bug**
I tired compose.folders.yml, got the following:
```
[xxx@xxx compose]$ docker compose -f compose.folders.yml up
validating /home/xniu/pulp-oci-images/images/compose/compose.folders.yml: services.pulp_web.depends_on.pulp_api must be a mapping
```
I changed a bit the compose.folders.yml, added the two condition statements for pulp_api and pulp_content, then the above problem gone:
```
  pulp_web:
    image: "pulp/pulp-web:latest"
    command: ['/usr/bin/nginx.sh']
    depends_on:
      pulp_api:
        condition: service_healthy
      pulp_content:
        condition: service_healthy
```

**To Reproduce**
just run `docker compose -f compose.folders.yml up`

**Expected behavior**
docker compose CLI should be able to run.
